### ISSUE TITLE
Compound bow, fine screwing for, loosening limbs

### ISSUE THREAD

**Issue by gdom2000** [Kenan2000/TerrainBASE-Archery-Pneumatics#2]
First of all, thank you for all your mods. You've brought new life to cata and for that I couldn't be more grateful.

Just wanted to bring this small issue to your attention. 
Loosening and tightening the limbs on the compound bow needs fine screwing 4. 
The lads on discord helped me figure it. This community is amazing honestly.

Anyway, I'll stop wasting your time now.
Hope yall are good :)

"str":"compoundbow(low)",
			"str_pl":"compoundbows(low)"
		},
		"ranged_damage":{
			"amount":18,
			"damage_type":"stab"
		},
		"type":"GUN",
		"use_action":{
			"menu_text":"TightenLimbs",
			"msg":"Youtightenthelimbs,increasingthestrengthofthebow.",
			"qualities_needed":{
				**"SCREW_FINE":4**
			},
			"target":"compbow",
			"type":"transform"
		}

**Comment by Kenan2000** [comment]
@gdom2000 Ah, I'm sorry, I've incorporated these mods into the Bright Nights Modpack https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack and my CDDA Modpack https://github.com/Kenan2000/CDDA-Kenan-Modpack, so get all the mods and more from these Modpacks, mate :-) 

And if you are interested, you can follow me and all the out-of-repo modders on our CDDA Community Modding server https://discord.gg/7GAXrQH
